# Generated by Django 4.2.29 on 2026-04-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.CharField(choices=[('etb', 'ETB'), ('ps', 'PS'), ('fas', 'FAS')], max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('build_qty', models.IntegerField(default=0)),
                ('build_location', models.CharField(blank=True, max_length=200)),
                ('bom_revision', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ready', 'Ready'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('on-hold', 'On Hold')], default='planned', max_length=20)),
                ('qty_produced', models.IntegerField(default=0)),
                ('qty_passed', models.IntegerField(default=0)),
                ('yield_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('customer_approval', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('conditional', 'Conditional'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pgm', models.CharField(max_length=100, verbose_name='Program Manager')),
                ('customer', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('color', models.CharField(default='#4f7ef8', max_length=7)),
                ('annual_volume', models.IntegerField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(choices=[('THB', 'THB'), ('USD', 'USD'), ('EUR', 'EUR')], default='THB', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('section', models.CharField(default='General', max_length=200)),
                ('remark', models.TextField(blank=True)),
                ('who', models.CharField(default='TBD', max_length=200)),
                ('days', models.IntegerField(default=1)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('inprogress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('', '— None —'), ('etb', 'ETB'), ('ps', 'PS'), ('fas', 'FAS')], default='', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
            ],
            options={
                'ordering': ['sort_order', 'start'],
            },
        ),
        migrations.CreateModel(
            name='NREItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Stencil', 'Stencil'), ('Jig Fixture', 'Jig Fixture'), ('Test Fixture', 'Test Fixture'), ('Pallet', 'Pallet'), ('Programming Fixture', 'Programming Fixture'), ('Tooling', 'Tooling'), ('Other', 'Other')], default='Stencil', max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('supplier', models.CharField(default='TBD', max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('THB', 'THB'), ('USD', 'USD'), ('EUR', 'EUR')], default='THB', max_length=3)),
                ('po_status', models.CharField(choices=[('no-po', 'No PO'), ('po-requested', 'PO Requested'), ('po-received', 'PO Received'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='no-po', max_length=20)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('due', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('stage', models.CharField(blank=True, choices=[('', '— None —'), ('etb', 'ETB'), ('ps', 'PS'), ('fas', 'FAS')], default='', max_length=10)),
                ('linked_tasks', models.ManyToManyField(blank=True, related_name='linked_nre', to='core.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nre_items', to='core.project')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('due', models.DateField(blank=True, null=True)),
                ('impact', models.CharField(blank=True, max_length=500)),
                ('stage', models.CharField(blank=True, choices=[('', '— None —'), ('etb', 'ETB'), ('ps', 'PS'), ('fas', 'FAS')], default='', max_length=10)),
                ('linked_tasks', models.ManyToManyField(blank=True, related_name='linked_issues', to='core.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.project')),
            ],
            options={
                'ordering': ['status', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='GateChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('checked', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_items', to='core.buildstage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='buildstage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.project'),
        ),
        migrations.AlterUniqueTogether(
            name='buildstage',
            unique_together={('project', 'stage_id')},
        ),
    ]
