# Generated by Django 5.2.12 on 2026-04-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dynamic_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplateSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('section', models.CharField(default='General', max_length=200)),
                ('who', models.CharField(default='TBD', max_length=200)),
                ('days', models.IntegerField(default=1)),
                ('stage_name', models.CharField(blank=True, help_text='Matched to BuildStage.name on the target project (case-insensitive).', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('depends_on', models.ManyToManyField(blank=True, help_text='Tasks that must finish before this task can start.', related_name='dependents', to='core.tasktemplate')),
                ('template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.tasktemplateset')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
