# Generated by Django 5.2.12 on 2026-04-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tasktemplateset_tasktemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='template_set',
        ),
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('depends_on_previous', models.BooleanField(default=False, help_text='If true, this section starts after all tasks in the previous section finish.')),
                ('day_offset', models.IntegerField(default=0, help_text='Days from project start date. Ignored if depends_on_previous is true.')),
                ('template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.tasktemplateset')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.sectiontemplate'),
        ),
    ]
