# Generated by Django 5.2.12 on 2026-04-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sectiontemplate_depends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='stage_name',
        ),
        migrations.AlterField(
            model_name='sectiontemplate',
            name='day_offset',
            field=models.IntegerField(default=0, help_text='Days from project start date. Ignored if depends_on is set.'),
        ),
    ]
