# Generated by Django 5.2.13 on 2026-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_stage_name_from_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='core.task'),
        ),
    ]
