# Generated by Django 5.2.13 on 2026-04-10 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_depends_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_major', models.PositiveIntegerField()),
                ('version_minor', models.PositiveIntegerField()),
                ('version_label', models.CharField(max_length=20)),
                ('change_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor')], default='minor', max_length=10)),
                ('change_comment', models.TextField()),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('task_snapshot', models.JSONField()),
                ('committed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_versions', to='core.project')),
            ],
            options={
                'ordering': ['-version_major', '-version_minor'],
                'unique_together': {('project', 'version_major', 'version_minor')},
            },
        ),
    ]
