# Generated by Django 5.2.13 on 2026-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_webhookconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookconfig',
            name='pa_token',
            field=models.CharField(blank=True, help_text='Secret token used in the subscribe URL to authenticate Power Automate.', max_length=64),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
