# Generated by Django 5.2.13 on 2026-04-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_webhookconfig_pa_token_alter_webhookconfig_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookconfig',
            name='recipient',
            field=models.EmailField(blank=True, help_text='Recipient email for chat webhooks. Leave blank for channel webhooks.', max_length=320),
        ),
    ]
