# Generated by Django 5.2.13 on 2026-04-11 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_webhookconfig_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('action', models.CharField(choices=[('create_issue', 'Create Issue'), ('update_task_status', 'Update Task Status'), ('update_stage_status', 'Update Build Stage Status'), ('create_task', 'Create Task')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, help_text='Scope to a specific project. Leave blank to require project_id in the payload.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_webhooks', to='core.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
