# Generated by Django 5.2.13 on 2026-04-12 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_customer_to_temp(apps, schema_editor):
    """Copy customer CharField to temporary customer_name field."""
    Project = apps.get_model('core', 'Project')
    for proj in Project.objects.all():
        proj.customer_name = proj.customer
        proj.save(update_fields=['customer_name'])


def create_customers_from_temp(apps, schema_editor):
    """Create Customer records from customer_name field."""
    Project = apps.get_model('core', 'Project')
    Customer = apps.get_model('core', 'Customer')

    # Get all unique customer names
    unique_names = Project.objects.values_list('customer_name', flat=True).distinct()

    # Create Customer records and link projects
    for customer_name in unique_names:
        if customer_name:  # Skip empty strings
            customer, _ = Customer.objects.get_or_create(name=customer_name)
            Project.objects.filter(customer_name=customer_name).update(customer=customer)


def reverse_migrate(apps, schema_editor):
    """Reverse: no-op for reversibility."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_task_assigned_to_issue_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create Customer model
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Add temporary customer_name field
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(
                max_length=200,
                blank=True,
                default='',
            ),
        ),
        # Copy customer CharField to customer_name
        migrations.RunPython(copy_customer_to_temp, reverse_code=reverse_migrate),
        # Remove old customer CharField
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        # Add new customer FK field
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects',
                to='core.customer'
            ),
        ),
        # Create Customer records from customer_name and link projects
        migrations.RunPython(create_customers_from_temp, reverse_code=reverse_migrate),
        # Remove temporary customer_name field
        migrations.RemoveField(
            model_name='project',
            name='customer_name',
        ),
        # Create UserProfile model
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pm', 'Project Manager'), ('engineer', 'Engineer'), ('customer', 'Customer')], default='engineer', max_length=20)),
                ('customer', models.ForeignKey(blank=True, help_text='Set only for customer role users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
