# Generated by Django 5.2.13 on 2026-04-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project_pgm_user_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildstage',
            options={'ordering': ['actual_date', 'planned_date']},
        ),
    ]
