# Generated by Django 5.2.13 on 2026-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_teammember_internal_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_code',
            field=models.CharField(blank=True, help_text='Product code or SKU', max_length=100),
        ),
    ]
