# Generated by Django 5.2.13 on 2026-04-13 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='unique_role_model_action',
        ),
        migrations.RemoveConstraint(
            model_name='userroleassignment',
            name='unique_user_role_project',
        ),
        migrations.AlterField(
            model_name='userroleassignment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='For customer-scoped access. If set, user can only view projects for this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='userroleassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.project'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'model_name', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='userroleassignment',
            unique_together={('user', 'role', 'project')},
        ),
    ]
