# Generated by Django 5.2.13 on 2026-04-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_rolepermission_unique_role_model_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroleassignment',
            options={'ordering': ['user', 'role_id']},
        ),
    ]
