# Generated by Django 5.2.13 on 2026-04-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_userroleassignment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('internal', 'Internal Only'), ('customer', 'Customer Only')], default='all', help_text='Controls who can see this issue', max_length=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('internal', 'Internal Only'), ('customer', 'Customer Only')], default='all', help_text='Controls who can see this milestone', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('internal', 'Internal Only'), ('customer', 'Customer Only')], default='all', help_text='Controls who can see this task', max_length=20),
        ),
    ]
