# Generated by Django 5.2.13 on 2026-04-13 04:43

from django.db import migrations, models


def set_internal_roles(apps, schema_editor):
    """Set is_internal flag for existing roles."""
    Role = apps.get_model('core', 'Role')
    
    # Internal roles: PM, Engineer, Admin
    Role.objects.filter(key__in=['pm', 'engineer', 'admin']).update(is_internal=True)
    
    # External roles: Customer
    Role.objects.filter(key='customer').update(is_internal=False)


def reverse_internal_roles(apps, schema_editor):
    """Reverse - reset all to default (True)."""
    Role = apps.get_model('core', 'Role')
    Role.objects.all().update(is_internal=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_visibility_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_internal',
            field=models.BooleanField(default=True, help_text='Internal roles can see internal-only tasks/milestones/issues'),
        ),
        migrations.RunPython(set_internal_roles, reverse_internal_roles),
    ]
