# Generated by Django 5.2.13 on 2026-04-13 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_issue_add_category_reported_by_resolution_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_summary',
            field=models.BooleanField(default=False, help_text='If true, this task aggregates progress from subtasks'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent task for work breakdown structure (max 2 levels recommended)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.task'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
