# Generated by Django 5.2.13 on 2026-04-14 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_task_parent_hierarchy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDueDateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_end', models.DateField()),
                ('new_end', models.DateField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_date_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_date_changes', to='core.task')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_changes', to='core.projectplanversion')),
            ],
            options={
                'ordering': ['-detected_at'],
                'unique_together': {('task', 'version')},
            },
        ),
    ]
