# Generated by Django 5.2.13 on 2026-04-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_taskduedatechange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildstage',
            name='bom_revision',
        ),
        migrations.RemoveField(
            model_name='buildstage',
            name='build_location',
        ),
        migrations.RemoveField(
            model_name='buildstage',
            name='qty_passed',
        ),
        migrations.RemoveField(
            model_name='buildstage',
            name='yield_pct',
        ),
    ]
