# Generated by Django 5.2.13 on 2026-04-14 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_taskduedatechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='affected_projects',
            field=models.ManyToManyField(blank=True, help_text='Projects affected by this program-level issue', related_name='program_issues', to='core.project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_program_level',
            field=models.BooleanField(default=False, help_text='True if this issue is tracked at program level (visible to Head of NPI)'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project-level issue. Leave blank for program-level issues.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.project'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='model_name',
            field=models.CharField(choices=[('program', 'Program'), ('project', 'Project'), ('buildstage', 'Build Stage'), ('milestone', 'Milestone'), ('task', 'Task'), ('issue', 'Issue'), ('teammember', 'Team Member'), ('nreitem', 'NRE Item'), ('gatechecklistitem', 'Gate Checklist Item'), ('projectplanversion', 'Project Plan Version'), ('tasktemplateset', 'Task Template Set'), ('webhookconfig', 'Webhook Config')], max_length=50),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='core.customer')),
                ('pgm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_programs', to=settings.AUTH_USER_MODEL, verbose_name='Program Manager')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program-level issue (spans multiple projects)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.program'),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program this project belongs to (groups projects under PGM/Customer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.program'),
        ),
    ]
